version: "3.8"

# Full-stack RAG deployment with Podman Compose
# Usage:
#   podman-compose up -d           # Start all services
#   podman-compose up -d rag-app   # Start just the RAG app (assumes Neo4j/Ollama running)
#   podman-compose logs -f rag-app # Follow logs
#   podman-compose down            # Stop all services

services:
  neo4j:
    image: neo4j:5.26.0
    container_name: neo4j
    ports:
      - "7474:7474" # HTTP Browser
      - "7687:7687" # Bolt protocol
    environment:
      - NEO4J_AUTH=neo4j/${NEO4J_PASSWORD:-changeme123}
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
    volumes:
      - neo4j-data:/data
      - neo4j-logs:/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7474"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    # Uncomment for GPU support:
    # devices:
    #   - nvidia.com/gpu=all
    # security_opt:
    #   - label=disable
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    ports:
      - "8080:8080"
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    volumes:
      - open-webui-data:/app/backend/data
    depends_on:
      ollama:
        condition: service_healthy
    restart: unless-stopped

  rag-app:
    build:
      context: .
      dockerfile: Containerfile
    image: pjs-neo-rag:latest
    container_name: pjs-neo-rag-app
    ports:
      - "8000:8000"
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASSWORD=${NEO4J_PASSWORD:-changeme123}
      - NEO4J_DATABASE=neo4j
      - EMBED_PROVIDER=ollama
      - CHAT_PROVIDER=ollama
      - OLLAMA_URL=http://ollama:11434
      - OLLAMA_EMBED_MODEL=${OLLAMA_EMBED_MODEL:-bge-m3}
      - OLLAMA_EMBED_DIM=${OLLAMA_EMBED_DIM:-1024}
      - OLLAMA_CHAT_MODEL=${OLLAMA_CHAT_MODEL:-mistral:7b}
      - API_PORT=8000
      - LOG_LEVEL=INFO
    volumes:
      # Mount your document directory for ingestion - CHANGE THIS PATH
      - ${SOURCE_DIR:-./corpus}:/app/documents:ro
      - rag-logs:/app/logs
    depends_on:
      neo4j:
        condition: service_healthy
      ollama:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped

volumes:
  neo4j-data:
  neo4j-logs:
  ollama-data:
  open-webui-data:
  rag-logs:
