version: '3.8'

services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    environment:
      - NEO4J_AUTH=neo4j/${NEO4J_PASSWORD:-yourpassword}
      - NEO4J_PLUGINS=["apoc"]
    volumes:
      - neo4j-data:/data
      - neo4j-logs:/logs
    restart: unless-stopped

  ollama:
    image: ollama/ollama:latest
    container_name: ollama-std
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    devices:
      - nvidia.com/gpu=all
    security_opt:
      - label=disable
    restart: unless-stopped

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    ports:
      - "3000:8080"
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    volumes:
      - open-webui-data:/app/backend/data
    depends_on:
      - ollama
    restart: unless-stopped

  rag-app:
    build: .
    container_name: pjs-neo-rag-app
    ports:
      - "8000:8000"
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASSWORD=${NEO4J_PASSWORD:-yourpassword}
      - NEO4J_DATABASE=neo4j
      - OLLAMA_URL=http://ollama:11434
      - OLLAMA_EMBED_MODEL=${OLLAMA_EMBED_MODEL:-bge-m3}
      - OLLAMA_CHAT_MODEL=${OLLAMA_CHAT_MODEL:-mistral:7b}
      - SOURCE_DIR=/app/documents
    volumes:
      # Mount your document directory - CHANGE THIS PATH
      - /mnt/ubuntustore/RAG-Docs:/app/documents:ro
    depends_on:
      - neo4j
      - ollama
    restart: unless-stopped

volumes:
  neo4j-data:
  neo4j-logs:
  ollama-data:
  open-webui-data:
